### ISSUE TITLE
Failed to provision volume with StorageClass "gluster-heketi-storageclass": not able to parse your claim Selector

### ISSUE THREAD

**Issue by marlon617** [engapa/zookeeper-docker#5] opened 2019-05-08 06:02 UTC
部署zk是无法创建pvc

![image](https://user-images.githubusercontent.com/5423846/57352902-629e7e80-7199-11e9-8ed6-0c0da0834ddd.png)

**Comment by engapa** [comment] 2019-05-11 19:17
Hi @marlon617, I guess you have an infrastructure with glusterFs installed, then you may follow this documentation at : 

- https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/dynamically_provisioning_pvs.html#glusterfs
- https://docs.okd.io/latest/install_config/storage_examples/gluster_dynamic_example.html
- https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/selector_label_binding.html

Beforehand, you'd need to create the suitable storage class, the persistent volume, and finally the volume claim with the suitable selector. 

Could you share your custom zk-persistent.yaml (based on the resource allocated in this repository) to take a look?

**Comment by engapa** [comment] 2019-05-11 19:29
I forgot something on last comment, you could be use a predefined selector by storage class instead of one selector by labels, here you have an example (for our zk-persistent.yaml resource):

```yaml
volumeClaimTemplates:
  ...
    spec:
      ...
      storageClassName: "glusterfs"
```
NOTE: "glusterfs" is the provisioner name of the storageclass resource with the heketi configuration

I hope it helps you !

**Comment by marlon617** [comment] 2019-05-28 08:25
Thank you！！！

又遇到了一个问题。。但是我修改为1000120000 也不行
![image](https://user-images.githubusercontent.com/5423846/58462624-d7dfec80-8164-11e9-9da5-536da804a67d.png)



  | whoami: unknown uid 1000120000
-- | --

**Comment by engapa** [comment] 2019-07-09 15:43
Well, the issue is because in your openshift cluster your account doesn't have a valid SCC to use any ID for the user 'zookeeper' and the group 'zookeeper' in the container.

By default you're using an account with default scc (restricted), that means that you must use an UID belongs to an specific range:

```bash
oc edit scc restricted
```
```yaml
...
runAsUser:
  type: MustRunAsRange
...
```

My tests run OK with Ubuntu VM on CircleCI as openshift host and using any UID because I create the new apps with an account with privileged SCC (take a look at script `main.sh` under openshift directory of this repo).
```bash
oc edit scc privileged
```
```yaml
...
runAsUser:
  type: RunAsAny
...
```
If you're deploying the zookeeper cluster on production environment and you don't have permission to manage SCCs for you account, then adjust in Dockerfile a valid value of the UID (now is 1001, for user and grouo) in the range and build a new image to be used in a new app (also adjust here the spec.securityContext.runAsUser value).

More details at:
- https://docs.openshift.com/enterprise/3.1/architecture/additional_concepts/authorization.html#security-context-constraints
- https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html

I hope helps !!

**Comment by engapa** [comment] 2019-07-15 11:22
Please if you find out any other issue create a new one, I'm going to close this referred to storage class.

Thx !

**Closed as completed** 2019-07-15 11:23 UTC
